# -*- coding: utf-8 -*-
"""Copy of FaceRecognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-z2t00zfQXz3nu5hPkfQ3OcYhYFJ81tl
"""

from matplotlib import pyplot as one_plot
import cv2

photo = cv2.imread("pr.png")
photo = cv2.cvtColor(photo , cv2.COLOR_BGR2RGB)

aio_model = cv2.CascadeClassifier("model.xml")
face = aio_model.detectMultiScale(photo)

a = face[0][0]
b = face[0][1]
c = face[0][2]
d = face[0][3]
photo = cv2.rectangle(photo , (a , b) , (a+c , b+d) , (120,255,150) , 7)

one_plot.imshow(photo)